#:schema node_modules/wrangler/config-schema.json
name = "metronome"
compatibility_date = "2024-08-06"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "metronome"
database_id = "6d164ac7-4793-4ccc-b6e6-be01084c1377"