// Generated by ts-to-zod
import { z } from "zod";

export const sectionMutationSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
  bpm: z.number().optional(),
  numberOfBeats: z.number().optional(),
  numberOfSubBeats: z.number().optional(),
  delay: z.number().optional(),
  numberOfBars: z.number().optional(),
});

export const sectionRecordSchema = sectionMutationSchema.and(
  z.object({
    id: z.number(),
    createdAt: z.string(),
    name: z.string(),
    bpm: z.number(),
    numberOfBeats: z.number(),
    numberOfSubBeats: z.number(),
    delay: z.number(),
    numberOfBars: z.number(),
  }),
);

export const songMutationSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  favorite: z.boolean().optional(),
  instrument: z.string().optional(),
  sections: z.array(sectionMutationSchema).optional(),
});

export const songRecordSchema = songMutationSchema.and(
  z.object({
    id: z.string(),
    createdAt: z.string(),
  }),
);

export const sectionTypeSchema = z.object({
  id: z.number(),
  name: z.string(),
  bpm: z.number(),
  numberOfBeats: z.number(),
  numberOfSubBeats: z.number(),
  delay: z.number(),
  numberOfBars: z.number(),
});

export const songTypeSchema = z.object({
  id: z.string(),
  name: z.string(),
  favorite: z.boolean(),
  instrument: z.string(),
  createdAt: z.string(),
  sections: z.array(sectionTypeSchema),
});
