// Generated by ts-to-zod
import { z } from "zod";

export const barMutationSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
  bpm: z.number().optional(),
  timeSignature: z.number().optional(),
  subBeats: z.number().optional(),
  delay: z.number().optional(),
  numberOfBars: z.number().optional(),
});

export const barRecordSchema = barMutationSchema.and(
  z.object({
    id: z.number(),
    createdAt: z.string(),
    name: z.string(),
    bpm: z.number(),
    timeSignature: z.number(),
    subBeats: z.number(),
    delay: z.number(),
    numberOfBars: z.number(),
  }),
);

export const songMutationSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  favorite: z.boolean().optional(),
  instrument: z.string().optional(),
  bars: z.array(barMutationSchema).optional(),
});

export const songRecordSchema = songMutationSchema.and(
  z.object({
    id: z.string(),
    createdAt: z.string(),
  }),
);

export const barTypeSchema = z.object({
  id: z.number(),
  songId: z.string(),
  name: z.string(),
  bpm: z.number(),
  timeSignature: z.number(),
  subBeats: z.number(),
  delay: z.number(),
  numberOfBars: z.number(),
});

export const songTypeSchema = z.object({
  id: z.string(),
  name: z.string(),
  favorite: z.boolean(),
  instrument: z.string(),
  createdAt: z.string(),
  bars: z.array(barTypeSchema),
});
